# Generated by Django 2.1 on 2018-08-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('account', '0004_auto_20180823_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='events',
            field=models.ManyToManyField(through='event.Membership', to='event.Event'),
        ),
    ]
