# Generated by Django 2.1 on 2018-08-27 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20180826_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='events',
        ),
    ]
