# Generated by Django 2.1 on 2018-08-29 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20180828_1056'),
        ('account', '0015_auto_20180828_1444'),
    ]

    operations = [
    ]
