# Generated by Django 2.1 on 2018-08-28 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_person_projects'),
        ('event', '0004_auto_20180827_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.Person'),
            preserve_default=False,
        ),
    ]
