# Generated by Django 2.1 on 2018-08-28 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='visibility',
            new_name='is_visible',
        ),
    ]
