# Generated by Django 2.1 on 2018-08-28 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_person_projects'),
        ('event', '0007_auto_20180828_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Person')),
            ],
        ),
    ]
