# Generated by Django 2.1 on 2018-08-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_eventmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_required',
            field=models.BooleanField(default=0),
        ),
    ]
