# Generated by Django 2.1 on 2018-08-29 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20180828_0936'),
        ('event', '0009_auto_20180828_1444'),
    ]

    operations = [
    ]
